version: "3.5"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  data:
    driver: ${VOLUMES_DRIVER}

services:
  app:
    build:
      context: ./
    container_name: "java-video"
    ports:
      - "${app_port}:8080"
    networks:
      - backend
    depends_on:
      - mysql
#    links:
#      - mysql
    environment:
      IP: mysql
      PORT: ${mysql_port}
      USERNAME: root
      PASSWORD: ${mysql_root_password}
      DATABASE: ${mysql_database}

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${mysql_port}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${mysql_root_password}"
      - "MYSQL_USER=${mysql_user}"
      - "MYSQL_PASSWORD=${mysql_password}"
      - "MYSQL_DATABASE=${mysql_database}"
    volumes:
      - ./docker-images/mysql/data:/var/lib/mysql
      - ./docker-images/mysql/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./docker-images/mysql/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - "PMA_ARBITRARY=1"
    ports:
      - "${phpmyadmin_port}:80"
    networks:
      - backend
    depends_on:
      - mysql
